# Generated by Django 5.2.11 on 2026-03-03 12:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/%Y/%m', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg', 'heic', 'heif', 'png'])]),
        ),
    ]
