# Generated by Django 5.2.11 on 2026-03-03 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmation',
            name='expiration_date',
            field=models.DateTimeField(null=True),
        ),
    ]
